name: CI

on:
  push:
    branches:
      - '*'

env:
  isNightly: ${{ contains(github.ref, 'dev') }}
  isFinalRelease: ${{ contains(github.ref, 'master') }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo snap install jq

    - name: Build (dev)
      if: ${{ env.isNightly == 'true' }}
      env:
        THAT_HASH: ${{ secrets.THAT_HASH }}
      run: chmod +x build && ./build dev

    - name: Build (pre-release)
      if: ${{ env.isFinalRelease == 'true' }}
      env:
        THAT_HASH: ${{ secrets.THAT_HASH }}
      run: chmod +x build && ./build final

    - name: Release Candidate
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isNightly == 'true'
      with:
        automatic_release_tag: latest-rc
        files: dist/sdcard.zip
        prerelease: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: latest-rc

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isFinalRelease == 'true'
      with:
        automatic_release_tag: latest-rc
        files: dist/sdcard.zip
        prerelease: false
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: stable
