name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
env:
  isNightly: ${{ contains(github.ref, 'dev') }}
  isReleaseCandidate: ${{ contains(github.ref, 'tags') && contains(github.ref, 'rc-') }}
  isFinalRelease: ${{ contains(github.ref, 'tags') && contains(github.ref, 'release-') }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo snap install jq

    - name: Build (dev)
      if: ${{ env.isNightly == 'true' }}
      env:
        THAT_HASH: ${{ secrets.THAT_HASH }}
      run: chmod +x build && ./build dev

    - name: Release (dev)
      if: env.isNightly == 'true'
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        tag : dev
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: dist/sdcard.zip

    - name: Update dev tag
      if: env.isNightly == 'true'
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: dist/sdcard.zip
        commit: dev
        prerelease: true
        replacesArtifacts: true
        tag : dev
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build (pre-release)
      if: ${{ env.isReleaseCandidate == 'true' }}
      env:
        THAT_HASH: ${{ secrets.THAT_HASH }}
      run: chmod +x build && ./build rc

    - name: Release (pre-release)
      if: env.isReleaseCandidate == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        artifacts: dist/sdcard.zip
        
    - name: Update latest-rc tag
      if: env.isReleaseCandidate == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-rc
        allowUpdates: true
        replacesArtifacts: true
        prerelease: true
        artifacts: dist/sdcard.zip

    - name: Build (final)
      if: env.isFinalRelease == 'true'
      run: ./build final

    - name: Release (final)
      if: env.isFinalRelease == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: dist/sdcard.zip

    - name: Update latest tag
      if: env.isFinalRelease == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        allowUpdates: true
        replacesArtifacts: true
        artifacts: dist/sdcard.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: sdcard
        path: dist/sdcard.zip